name: Close inactive issues
on:
  schedule:
    - cron: '30 1 * * *' # 每天定时运行
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          days-before-issue-stale: 14        # 14天不活跃标记为stale
          days-before-issue-close: 14        # stale后14天关闭
          stale-issue-label: "stale"
          stale-issue-message: "此 Issue 因超过 14 天未活动已被自动标记为陈旧（stale）。如果您认为它仍需处理，请留下评论或更新，我们将取消标记；否则，它将在 14 天后自动关闭。"
          close-issue-message: "此 Issue 因被标记为 stale 后超过 14 天未活动已被关闭。"
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.STALE_TOKEN }}